### ISSUE TITLE
Can a Job be Send and/or Sync?

### ISSUE THREAD

**Issue by sunshowers** [ohadravid/win32job-rs#1]
Hi there!

I wanted to use `win32job` in [cargo-nextest](https://nexte.st/), but I ran into an issue: a `Job` isn't `Send` or `Sync` (presumably because it contains a `HANDLE`, which is a wrapper around a `*const`).

I was wondering if it's safe for a job to be `Send` and/or `Sync`? As far as I know, that's fine (after all, a `std::process::Child` is `Send` and `Sync`).

For now I can implement my own wrapper around a `Job`.

**Comment by ohadravid** [comment]
Hi!

I think you are correct.
The MSDN docs don't _specifically_ say that, but they usually specify if something is **isn't** `Send/Sync`.

I'll add this and publish a new version 😄 

Thanks!

**Comment by ohadravid** [comment]
Fixed in [1.0.2](https://github.com/ohadravid/win32job-rs/releases/tag/v1.0.2) 🎉
