### ISSUE TITLE
What I am doing wrong here?

### ISSUE THREAD

**Issue by bukowa** [ohadravid/win32job-rs#7]
Link to full code is here: https://gist.github.com/bukowa/751b1b307e6e0f08d0ab117cc09a4c1c

In short, when below `spawn` method fails - rust process exit with code 0:

```rust
fn main() -> Result<(), std::io::Error> {
...
    // Paste code from win32job example ^^
    let job = win32job::Job::create().unwrap();
    let mut info = job.query_extended_limit_info().unwrap();
    info.limit_kill_on_job_close();
    job.set_extended_limit_info(&mut info).unwrap();
    job.assign_current_process().unwrap();
...
    .spawn()
    .map_err(|e| io::Error::new(ErrorKind::Other, format!("win32die: {}: {}", command, e)))?;
````

But delete win32job and it just works:
```rust
fn main() -> Result<(), std::io::Error> {
...
...
    .spawn()
    .map_err(|e| io::Error::new(ErrorKind::Other, format!("win32die: {}: {}", command, e)))?;
````

Or change to `expect` and it just works:
```rust
fn main() -> Result<(), std::io::Error> {
...
    // Paste code from win32job example ^^
    let job = win32job::Job::create().unwrap();
    let mut info = job.query_extended_limit_info().unwrap();
    info.limit_kill_on_job_close();
    job.set_extended_limit_info(&mut info).unwrap();
    job.assign_current_process().unwrap();
...
    .spawn()
    .expect("Failed to execute command");                               <---------changed
````

**Comment by ohadravid** [comment]
Hi @bukowa 👋 

I tried running the gist (which has the job + spawn) and it seems to work as expected:
```
PS C:\Workspace\playground> .\target\debug\playground.exe -- ping -n 3 4.2.2.4

Pinging 4.2.2.4 with 32 bytes of data:
Reply from 4.2.2.4: bytes=32 time=72ms TTL=55
Reply from 4.2.2.4: bytes=32 time=73ms TTL=55
Reply from 4.2.2.4: bytes=32 time=73ms TTL=55

Ping statistics for 4.2.2.4:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 72ms, Maximum = 73ms, Average = 72ms
PS C:\Workspace\playground>
```

However, I might be misunderstanding something so let me know if something different is expected in this case

**Comment by bukowa** [comment]
> Hi @bukowa 👋
> However, I might be misunderstanding something so let me know if something different is expected in this case

Hey! Sorry, I said `In short, when below spawn method fails - rust process exit with code 0:` but it's not clear I guess.
Can you try with command that fails, like `.\target\debug\playground.exe -- this-should-fail`

**Comment by ohadravid** [comment]
> command that fails, like .\target\debug\playground.exe -- this-should-fail

Ah! I understand now. So the problem is that once `job` is dropped (which is caused by the early returning of `?`), using both `limit_kill_on_job_close` and `assign_current_process` will kill the current process (resulting in the exit code 0).

The easiest solution in this case is probably to "leak" the `job` using

```rust
job.assign_current_process().unwrap();

std::mem::forget(job);
```

**Comment by bukowa** [comment]
> > command that fails, like .\target\debug\playground.exe -- this-should-fail
> 
> Ah! I understand now. So the problem is that once `job` is dropped (which is caused by the early returning of `?`), using both `limit_kill_on_job_close` and `assign_current_process` will kill the current process (resulting in the exit code 0).
> 
> The easiest solution in this case is probably to "leak" the `job` using
> 
> ```rust
> job.assign_current_process().unwrap();
> 
> std::mem::forget(job);
> ```

Or start the `job` after `spawn` method? ^^

**Comment by ohadravid** [comment]
> Or start the job after spawn method?

But then the child is not assigned to the job, and if the parent process dies the child will not be terminated (which is probably not what you want).

**Comment by bukowa** [comment]
> > Or start the job after spawn method?
> 
> But then the child is not assigned to the job, and if the parent process dies the child will not be terminated (which is probably not what you want).
> 
> (You can `job.assign_process(child.as_raw_handle() as _)`, but then you still have a short time where the child is unassigned and might leak)

Hmm, how can I write a wrapper that doesn't have this problem? Perhaps I should describe it a bit better. I want to publish this binary on Cargo so that I can use `cargo install win32die` and then use it wherever I need *I tried googling for such a tiny wrapper but couldn't find one. However, as you can see, I don't fully understand the problem. Would this be within the scope of a feature request?

**Comment by ohadravid** [comment]
If I understand correctly, you really should just "leak" the job using `forget` (this doesn't leak any memory - it just wont close the job object).

Otherwise, can you show a few more examples of how you would use `win32die`?

**Comment by bukowa** [comment]
Regarding how I would like to use win32die, I would like it to be a wrapper that ensures that anything it spawns will always be killed when win32die exits. Something like process groups in Linux? For example, win32 -> process1 -> (process1 spawning more processes) ... -> win32 dies, all of these processes die. Are there any downsides to using  `forget`?

**Comment by ohadravid** [comment]
> Are there any downsides to using forget?

None 🥳

**Comment by bukowa** [comment]
> > Are there any downsides to using forget?
> 
> None 🥳 (You can also use `job.into_handle()` which is equivalent)

Great ^^ is it also a solution to the above problem? I am wondering if `is there a better way` in Windows to somehow simulate the process group killing?

**Comment by bukowa** [comment]
Thanks a lot for help. I published it here and it works for me https://github.com/bukowa/w32die
